import {
  FetchDashboardData,
  BottomNavBar,
  SideNavBar,
  TopNavBar,
} from "@/features/provider/dashboard";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Appointly dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <FetchDashboardData>
      <div className="flex min-h-screen">
        <SideNavBar />

        <div className="flex-1 flex flex-col min-w-0">
          <TopNavBar title="Appointments" />

          <main className="flex-1 p-4 md:p-8 max-w-7xl w-full">{children}</main>
        </div>

        <BottomNavBar />
      </div>
    </FetchDashboardData>
  );
}
