

import type { Metadata } from "next";
import {
  FetchDashboardData,
} from "@/features/provider/dashboard-service";


export const metadata: Metadata = {
  title: "Appointly dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <FetchDashboardData>
      {children}
    </FetchDashboardData>
  );
}
