import { FetchServices } from "@/features/services-listing";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Appointly | Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <FetchServices>{children}</FetchServices>;
}
