import type { Metadata } from "next";
import { FetchUserProfileData } from "@/features/user/account";
import SideBar from "./Sidebar";

export const metadata: Metadata = {
  title: "Appointly | Manage Account",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <FetchUserProfileData>
      <div className="flex max-w-[1440px]">
        <SideBar />
        <main className="flex-1 bg-transparent">{children}</main>
      </div>
    </FetchUserProfileData>
  );
}
