import type { Metadata } from "next";
import { FetchUserProfileData } from "@/features/account";

export const metadata: Metadata = {
  title: "Appointly | Manage Account",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <FetchUserProfileData>{children}</FetchUserProfileData>;
}
